### ISSUE TITLE
syntax error when running bibtex2htmldiv.bib2html

### ISSUE THREAD

**Issue by i2000s** [ketch/tex2_rst_html#1]
Hi David,

This tool seems interesting, but I run into errors. What I did is going into the bib directory and running

```
import bibtex2htmldiv
bibtex2htmldiv.bib2html('Publications.bib')
```

Then the error message is `bash: syntax error near unexpected token`'Publications.bib''`. I have changed the dest-directories in the python code. Did I missed anything?

Thanks,
Qi

**Comment by ketch** [comment]
Those commands need to be run from a Python or IPython interpreter prompt, not from the shell.  Sorry if that wasn't clear.

**Comment by i2000s** [comment]
Thank you for clarifying. If you can update the README file as well, that would be very nice for future readers!

BTW, I found your site and Python scripts very useful. I am building my NoteBlog upon yours now.

Cheers,
Qi

**Comment by ketch** [comment]
Glad to hear it!  I think most users know that `import` is a Python command and not a shell command, but I updated the docstring in any case.
